mpollmeier/gremlin-scala

- src/main/scala/gremlin/scala/GremlinScala.scala
- src/test/scala/gremlin/scala/AndSpec.scala
- src/test/scala/gremlin/scala/LogicalSpec.scala
- src/test/scala/gremlin/scala/TraversalSpec.scala
Add `And` and `Or` steps according to http://tinkerpop.incubator.apache.org/docs/3.0.0.M9-incubating/#and-step
> Add `And` and `Or` steps

- src/main/scala/gremlin/scala/ScalaGraph.scala
- src/test/scala/gremlin/scala/MarshallerSpec.scala
Save/Load for Collections as requested https://github.com/mpollmeier/gremlin-scala/issues/73
> Save/Load for Collections

- src/main/scala/gremlin/scala/ScalaVertex.scala
- src/main/scala/gremlin/scala/SemiEdge.scala
- src/test/scala/gremlin/scala/ArrowSyntaxSpec.scala
I propose this syntax sugar to add edges.
> Arrow syntax

- src/main/scala/gremlin/scala/package.scala
We have the wrap functions but the unwrap functions are missing
> unwrap functions

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaElement.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaGraph.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
- gremlin-scala/src/main/scala/gremlin/scala/package.scala
- macros/src/main/scala/gremlin/scala/Marshallable.scala
- Replaced funny arrow char by a real => to avoid issues in Idea
- Implemented a maximum of the Graph interface function in other to keep the user in the Scala world
> Implemented a maximum of the Graph interface

- gremlin-scala/src/main/scala/gremlin/scala/ScalaGraph.scala
graph.transactional { graph =>
graph.addVertex(...)
graph.addVertex(...)
...
}
does all actions in ACID
> Transactional shorthand until we get the 2.12 Java Lambda interop

- README.md
- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
- gremlin-scala/src/main/scala/gremlin/scala/Schema.scala
- gremlin-scala/src/main/scala/gremlin/scala/package.scala
- gremlin-scala/src/test/scala/gremlin/scala/ArrowSyntaxSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/ElementSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/SchemaSpec.scala
* now all arrow syntax cases have the same syntax for defining edge properties. and actually work :)
* cleaning up tests
> Arrowspec fix

- src/main/scala/com/tinkerpop/gremlin/package.scala
See https://github.com/mpollmeier/gremlin-scala/issues/122
> #122: Type is not inferred correctly for ->[S] aliases

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
> Added `foldLeft` wrapper

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
Initial implementation, so feedback appreciated.
> Implementation of `choose` and `constant` for #131

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
Includes `constant`, which is also a part of `choose` PR.
> Implementation of coalesce. #137

- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
- gremlin-scala/src/test/scala/gremlin/scala/ArrowSyntaxSpec.scala
* Added Method for edge creation which take Map as a properties.
* Added unit test
> Implement method for edge creation which take Map as a properties.

- build.sbt
- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaEdge.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaElement.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaGraph.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
- gremlin-scala/src/main/scala/gremlin/scala/Schema.scala
- gremlin-scala/src/main/scala/gremlin/scala/package.scala
- gremlin-scala/src/test/scala/gremlin/scala/ElementSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
* rename key.value to key.name
* less use of implicit by moving KeyOps into case class Key
> refactor key operations

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
> Fix and/or steps type issue

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/ElementSpec.scala
> Allow varying types for hasValue

- gremlin-scala/src/test/scala/gremlin/scala/FilterSpec.scala
Some tests from apache TP3 were added
> Port over more steps from filter package of TP3

- gremlin-scala/src/main/scala/gremlin/scala/ScalaEdge.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
- gremlin-scala/src/main/scala/gremlin/scala/dsl/AnonymousVertex.scala
- gremlin-scala/src/main/scala/gremlin/scala/dsl/Converter.scala
- gremlin-scala/src/test/scala/gremlin/scala/MarshallableSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/dsl/DslSpec.scala
- macros/src/main/scala/gremlin/scala/Annotations.scala
- macros/src/main/scala/gremlin/scala/Marshallable.scala
- macros/src/main/scala/gremlin/scala/id.scala
- macros/src/main/scala/gremlin/scala/label.scala
- project/build.properties
allows to access the underlying element from a marshalled case class
> @underlying for marshallable macro

- macros/src/main/scala/gremlin/scala/Marshallable.scala
Improves macro hygiene by using fully qualified class references.
https://docs.scala-lang.org/overviews/quasiquotes/hygiene.html
> Improve macro hygiene (qualify class references)

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/main/scala/gremlin/scala/ProjectionBuilder.scala
- gremlin-scala/src/test/scala/gremlin/scala/ProjectSpec.scala
supersedes https://github.com/mpollmeier/gremlin-scala/pull/271/
> type safe `project` step by To-om

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/SelectSpec.scala
> Add select by column (keys and values)

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
I suggest a new method signature for `match` step which accept a list of functions.
> Refactor match step

- build.sbt
- gremlin-scala/src/test/scala/gremlin/scala/SelectSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalStrategySpec.scala
thanks @to-om https://github.com/mpollmeier/gremlin-scala/issues/285
> scala 2.13.0

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
re https://gitter.im/mpollmeier/gremlin-scala?at=6019f4d584e66b7f7eca582b
> .addE step doesn't need and shouldn't have `<:< Vertex` constraint

- build.sbt
- gremlin-scala/src/main/scala/gremlin/scala/GraphHelper.scala
- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaEdge.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaElement.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
- gremlin-scala/src/main/scala/gremlin/scala/SemiEdge.scala
- gremlin-scala/src/main/scala/gremlin/scala/dsl/NodeSteps.scala
- gremlin-scala/src/main/scala/gremlin/scala/dsl/Steps.scala
- gremlin-scala/src/test/scala/gremlin/scala/AlgorithmSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/ArrowSyntaxSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/ElementSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/FilterSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/GraphHelperSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/GraphSerialisationSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/LogicalSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/MonadSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/PSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/ProjectSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/SchemaSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/SelectSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/TestBase.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalStrategySpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/dsl/DslSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/marshallable/MarshallableSpec.scala
- macros/src/main/scala/gremlin/scala/Marshallable.scala
- project/build.properties
1. Lib upgrades (Scalatest, scalamock, shapeless, Tinkerpop, etc)
2. Fixed all the warnings about Auto-application deprecation (easier transition to Scala 3)
3. Fixed a couple of easy deprecation warnings from Tinkerpop
> Library upgrade

- build.sbt
- gremlin-scala/src/main/scala/gremlin/scala/ScalaGraph.scala
- gremlin-scala/src/main/scala/gremlin/scala/SelectAllStep.scala
- gremlin-scala/src/main/scala/gremlin/scala/TraversalSource.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalStrategySpec.scala
Use Gremlin version 3.5.1 and fix the code.
Fixes #304
> Gremlin 3.5.1

- build.sbt
- project/build.properties
- project/plugins.sbt
- gremlin 3.5.3
- scala 2.13.8
- plugin versions bump
> [gremlin] bump 3.5.3

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
> Remove TupleWithValue
