- build.sbt
- src/main/scala/gremlin/scala/SafeMapper.scala
- src/main/scala/gremlin/scala/ScalaGraph.scala
- src/main/scala/gremlin/scala/ScalaVertex.scala
- src/test/scala/gremlin/scala/MarshallerSpec.scala
After talking about compile time save/load from #73 , I added `load` and `save` that uses shapeless in compile time to do the conversion and it's fully typed safe. It also works with nested case classes like:
```scala
case class Person(name:String, age:Int, address:Address)
case class Address(zip:Int, street:String)
val jack = Person("Jack", 20, Address(11111, "Jefferson"))
```
it's very simple at user end:
```scala
val v = gs.save(jack)
val jackV = v.load[Person]
```
I deleted the existing reflection based code for `save` but I left the method `load` in package object. We can also delete that because I already added `load` in `ScalaVertex`. 
`load` also returns `Option` so it's safe if someone cast it wrong. Two new test cases also has been added for nested case classes. I also should …
> Compile time load and save, #73

- src/main/scala/gremlin/scala/ScalaVertex.scala
- src/main/scala/gremlin/scala/SemiEdge.scala
- src/test/scala/gremlin/scala/ArrowSyntaxSpec.scala
Added support for passing varargs of pairs to set the properties of the Edge after adding it.  
Should this syntax be altered to be compatible with blueprints-scala (recognizably obsolete) which is different as shown.  I would love to expand this and be more involved in this project.
```
hercules --> "father" --> jupiter
jupiter <--> "brother" <--> neptune
```
> SemiEdge enhancement

- gremlin-scala/src/main/scala/gremlin/scala/ScalaEdge.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaElement.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaGraph.scala
- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
- gremlin-scala/src/main/scala/gremlin/scala/SemiEdge.scala
- gremlin-scala/src/main/scala/gremlin/scala/package.scala
- gremlin-scala/src/test/scala/gremlin/scala/ArrowSyntaxSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/ElementSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/FilterSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/LabelledPathSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/LogicalSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/SchemaSpec.scala
@joan38 @dkrieg I'm not sure about this one... 
The goal is to make it less intrusive, i.e. only convert to ScalaVertex/ScalaEdge if needed. Which means that in some situations we need an extra call to `asScala`. Please let me know your thoughts.
> use java types by default

- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
When the change was made to swap String keys for the Key\[A] case class, an infinite loop was introduced where property\[A](Cardinality, Key\[A], A, AnyRef*) calls itself.
> Remove infinite recursion in ScalaVertex.property

- build.sbt
Shapeless 2.3 has just been released—lots of bugfixes and
enhancements without any breaking API changes:
http://milessabin.com/blog/2016/02/25/shapeless-2.3.0/
Also bumped the patch version of scala-xml. It was the only thing left
depending on scala-library <2.11.7, so bumping it cleans up all eviction
notices.
> Upgrade shapeless to 2.3.0

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
From the best I can tell, introducing a default ordering is the cause of the bug, given that vertexes and edges don't have an implicit ordering. Not sure what the broader implications are of making this change.
> Fix for ClassCastException when using `order().by(...)`

- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
- gremlin-scala/src/test/scala/gremlin/scala/MarshallableSpec.scala
For #156 . 
Went with `updateWith` since the method is not actually ensuring a 1:1 correspondence with a case class, it only uses the provided instance as a "template". For example, it's entirely possible to apply `updateWith` on the same vertex using two case classes of different types - although no idea why'd one want that :).
On the other hand, this also allows for fail-safe handling of changes within your data model (e.g. new fields).
Tried to emulate the style. Went with a single, corner-case full test case, since we're not actually testing serialization _per se_, only its "derivative" use.
> Added ability to update a vertex with a case class

- build.sbt
- gremlin-scala/src/test/scala/gremlin/scala/GremlinStandardTestSuite.scala
- version.sbt
Having double-checked the upgrade notes:
http://tinkerpop.apache.org/docs/3.2.1/upgrade/#_tinkerpop_3_2_1
it looks like the test suite change was the only one relevant to `gremlin-scala` itself. Also, I hope that I got the versioning correctly.
> Bumped to 3.2.1 upstream.

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- The `GraphTraversal` API called by this method accepts `Long` values.
> GremlinScala.range() methods now accepts 'Long' attributes

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
JavaConverters can wrap Java List as Scala buffer avoiding traversing the list and copying its content so it would improve performance and memory usage a bit.
> Add toBuffer() to GremlinScala

- build.sbt
- gremlin-scala/src/main/scala/gremlin/scala/TraversalSource.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalStrategySpec.scala
To better facilitate RemoteConnection-based GraphTraversalSource
implementations, adds withRemote methods to TraversalSource.
See discussion in #118 for more details
> Add TraversalSource.withRemote for Remote Traversal Support

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
The Graph step (V()) can be used mid-traversal (i.e.:
http://tinkerpop.apache.org/docs/current/reference/#graph-step).
Defining it in GremlinScala allows V() to be used in this way.
Noticed this while trying to connect two vertices with an edge using a traversal.
> Allow V() to be used mid-traversal

- gremlin-scala/src/main/scala/gremlin/scala/ScalaGraph.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
Similar to ScalaGraph.V() and E(), adds addV() and inject() which use
the graph's traversal source to begin a new traversal.
addV() in particular is useful when using a remote traversal source as
it is possible that a withRemote created traversal source uses an
EmptyGraph and thus addVertex() will not work.
See discussion in #118 for more details
> Add addV() and inject() to ScalaGraph

- gremlin-scala/src/main/scala/gremlin/scala/ScalaElement.scala
- gremlin-scala/src/test/scala/gremlin/scala/ElementSpec.scala
implements to opposite of gremlin.scala.ScalaElement#valueOption
if value is defined sets the property, if not removes it
> setter for Option values on ScalaElement

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
note: when using with addE, it only selects the first vertex!
http://tinkerpop.apache.org/docs/current/reference/#from-step
https://groups.google.com/forum/#!topic/gremlin-users/3YgKMKB4iNs
> add `to` and `from` modulators that take traversals

- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
This change ensures that head and headOption steps will limit
traversals to a single result, rather than executing a full traversal,
throwing away the tail, and then returning only the head.  This is
especially important when connecting to a remote GremlinServer, or
when a local Graph connects to a remote storage backend, where query
latencies can be quite large.
> Add limit(1) to head/headOption

- build.sbt
- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/marshallable/MarshallableSpec.scala
- macros/src/main/scala/gremlin/scala/Annotations.scala
- macros/src/test/scala/gremlin/scala/AnnotationsSpec.scala
In cases where a domain CC was labeled using a constant value, rather
than a simple literal string, GremlinScala.hasLabel[CC] would fail
to find the correct label, and would fall back to the class name.  This
change adds some utilities for resolving labels by CC, so that these
can be correctly resolved.
fixes #252
> Fix GremlinScala.hasLabel[CC] w/ constant label

- gremlin-scala/src/test/scala/gremlin/scala/marshallable/MarshallableSpec.scala
- macros/src/main/scala/gremlin/scala/Marshallable.scala
Fixes an issue where the marshallable macro emits code that fails to
compile when an optional property's underlying value is an AnyVal with
no valueGetter.
fixes #257
> Handle optional predefined AnyVals in Marshallable

- macros/src/main/scala/gremlin/scala/Marshallable.scala
Just a small tweak to Marshallable#fromCC to fix compiler warnings (and allow for use of -Xfatal-warnings)
> Fix Marshallable#fromCC warnings

- gremlin-scala/src/main/scala/gremlin/scala/ScalaElement.scala
- gremlin-scala/src/main/scala/gremlin/scala/TraversalSource.scala
* Use inject when starting a traversal from an element rather than an
anonymous traversal. Initializing a traversal in this manner maintains
a reference to the element's graph, which allows for using steps that
mutate the graph (e.g. adding a vertex or edge). An anonymous
traversal's graph is EmptyGraph, which is immutable.
* Use underlying graph's traversal source when initializing a
gremlin-scala TraversalSource. Supports use cases where the underlying
graph provides a custom GraphTraversalSource implementation.
> Minor traversal source/start fixes

- macros/src/main/scala/gremlin/scala/Marshallable.scala
This brings back a fix that was removed in 3.3.4.7 to avoid compiler warnings when a property value's type cannot be null.
Since updating to 3.3.4.7, we've also been seeing dead code errors after calls to the DSL's select step. This PR also addresses this issue. Unfortunately, I have not yet been able to get a simple reproducible example together to contribute to DSLSpec, however it would appear to also be related to the fix for #265.  Fundamentally, the problem in #265 occurs when fromCCParams is empty. When the empty fromCCParams gets spliced into immutable.List.apply, the type of the resulting List is `List[Nothing]` (hence the _2 is not a member of Nothing errors).  Explicitly providing a type parameter to List fixes the issues.
> Fix Marshallable's fromCC

- .gitignore
- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
This is to address the issue here: https://github.com/mpollmeier/gremlin-scala/issues/280
This simply provides a wrapper which exposes the side effects of a traversal via the admin interface of the traversal.
> Add getSideEffects Via Key Value

- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
Adding a test that verifies you can limit the output of a `.path` recipe using alias steps in conjunction with `.from` and `.to`. Included By modulators cause why not
> Add test for path/from/to with By modulators

- build.sbt
When including `gremlin-scala` as a dependency I want to have an option
to include a version compiled to a specific Scala version.
Currently, including `gremlin-scala` means that `scala-reflect` 2.13.1
joins the party always which is not necessairly desired, due to binary
incompatibilities between 2.13.0 and 2.13.1.
> Cross-compile to 2.13.0 as well

- README.md
- gremlin-scala/src/test/scala/gremlin/scala/marshallable/MarshallableSpec.scala
- macros/src/main/scala/gremlin/scala/Marshallable.scala
This is a small change to Marshallable to handle Set properties. This gives us a natural way to represent vertex properties with `set` cardinality in case classes. Note that this is breaking change; the previous behaviour was to treat these as standard properties, i.e. `single` cardinality in which the value is the entire set object.
> Handle Set properties in Marshallable

- gremlin-scala/src/main/scala/gremlin/scala/ScalaVertex.scala
Updates ScalaVertex.addEdge to use a TraversalSource supplied via an
implicit ScalaGraph rather than creating a new default/unconfigured
TraversalSource on the underlying element's graph.
> Updates ScalaVertex.addEdge to accept implicit ScalaGraph

- build.sbt
- project/build.properties
sbt < 1.5.1 will stop working in a few days due to the bintray sunset
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
> upgrade scala and sbt

- gremlin-scala/src/main/scala/gremlin/scala/By.scala
- gremlin-scala/src/main/scala/gremlin/scala/GremlinScala.scala
- gremlin-scala/src/test/scala/gremlin/scala/SelectSpec.scala
- gremlin-scala/src/test/scala/gremlin/scala/TraversalSpec.scala
Although the group method is defined so that the type of `g.V().group(By.label,  By(__[Vertex]().count()).head().get("label")` becomes `JCollection[Long]`, the type at runtime is actually `Long`.
> Fix typing bug of group(By(...), By(traversal))
